### ISSUE TITLE
Hidden tabs not exposed when expanding

### ISSUE THREAD

**Issue by davist11** [vigetlabs/craft-sidebartoggle#4]
![image](https://user-images.githubusercontent.com/199985/80733784-2bc52500-8adc-11ea-97f1-ea4b35a1014e.png)

When there are lots of tabs (including hidden ones), expanding doesn't show additional tabs. Manually resizing the window does, so we should be able to trigger a window resize with expanding/collapsing the sidebar.

**Comment by gregkohn** [comment]
Resolved by `v3.0.2`
